db:
    admin_user: dapadmin
    admin_pass: 123qwe
    shared_db: sdata
    addr: 127.0.0.1
    port: 3306

redis:
    addr: 127.0.0.1
    port: 6379
    enabled: True
    expire: 300

log:
    level: WARNING
